config/routes.rb
Rails.application.routes.draw do
 
  get 'microposts/create'

  get 'microposts/destroy'

  get 'password_resets/new'

  get 'password_resets/edit'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'sessions/new'

  get 'users/new'

  get '/help' => "static_pages#help"

  get '/about' => "static_pages#about"

  get '/contact' => "static_pages#contact"

  get '/signup' => "users#new"

  post '/signup' => "users#create"

  root 'static_pages#home'

  get '/login' => "sessions#new"

  post '/login' => "sessions#create"

  delete '/logout' => "sessions#destroy"

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :relationships, only:[:create, :destroy]

  resources :account_activations, only:[:edit]

  resources :password_resets, only:[:new, :create, :edit, :update]

  resources :microposts, only:[:create, :destroy]

end

app/models/user.rb
class User < ApplicationRecord

	has_many :microposts, dependent: :destroy
	#followers - followeds, Many-to-many association through Model Relationship(follower_id followed_id)
	#one user has many following
	#one user has many followers
	has_many :active_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
	has_many :following, through: :active_relationships, source: :followed
	has_many :passive_relationships, foreign_key: "followed_id", class_name: "Relationship", dependent: :destroy
	has_many :followers, through: :passive_relationships, source: :follower

	attr_accessor :remember_token, :activation_token, :reset_token
	before_save{self.email.downcase!}
	before_create :create_activation_digest
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates(:name, presence: true, length: {maximum: 50})
	validates(:email, presence: true, length: {maximum: 255}, format: {with: VALID_EMAIL_REGEX},
		uniqueness: {case_sensitive: false})
	has_secure_password
	validates(:password, presence:true, length:{minimum:6}, allow_nil:true)


	def self.new_token
		SecureRandom.urlsafe_base64
	end

	def self.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    	BCrypt::Password.create(string, cost: cost)
	end

	def remember
		@remember_token = User.new_token
		update_attribute(:remember_digest, User.digest(@remember_token))
	end

	def authenticate?(attribute, token)
		digest = send("#{attribute}_digest")
		if digest == nil
			return false
		else
			BCrypt::Password.new(digest).is_password?(token)
		end
	end

	def forget
		update_attribute(:remember_digest, nil)
	end

	def activate
		update_attribute(:activated, true)
		update_attribute(:activated_at, Time.zone.now)
	end

	def send_activation_email
		UserMailer.account_activation(self).deliver_now		
	end

	def send_password_reset_email
		UserMailer.password_reset(self).deliver_now
	end

	def create_reset_digest
		@reset_token = User.new_token
		update_attribute(:reset_digest, User.digest(@reset_token))
		update_attribute(:reset_send_at, Time.zone.now)
	end

	def reset_link_expired?
		self.reset_send_at < 2.hours.ago
	end

	def feed
	#	feed = Micropost.where(user_id: self.id)
	
	#   too much enquiries
	#	feed = self.microposts
	#	self.following.each do |followed|
	#		feed << followed.microposts
	#	end

		following_id = "SELECT followed_id FROM relationships WHERE follower_id = :user_id"
		feed = Micropost.where("user_id IN (#{following_id}) OR user_id = :user_id", user_id: self.id)

	end

	def follow(other_user)
		# active_relationships.create(followed_id: other_user.id) unless other_user.nil?
		following << other_user unless other_user.nil?
	end

	def unfollow(other_user)
	#	unless other_user.nil?
	#		r = active_relationships.find_by(followed_id: other_user.id) 
	#		r.destroy if r
	#	end
		following.delete(other_user)
	end

	def following?(other_user)
		following.include?(other_user)
	end

	private

	def create_activation_digest
		@activation_token = User.new_token #can also use self.activation_token
		self.activation_digest = User.digest(@activation_token)

	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :logged_in_user, only: [:edit, :update, :index, :destroy, :following, :followers]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: [:destroy]

 
  def show
  	@user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
    redirect_to root_path unless @user.activated
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      @user.send_activation_email
      flash[:success] = "Please check your email to activate the account."
      redirect_to root_path
 #     log_in(@user)
 # 		flash[:success] = "Welcome to the Sample App!"
 # 		redirect_to user_path(@user)
  	else
  		render "new"
  	end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:sucess] = "You've successfully updated your profile."
      redirect_to user_path(@user)
    else
      render "edit"
    end
  end

  def index
      @users = User.where(activated:true).paginate(page:params[:page])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = "User deleted"
    redirect_to users_path
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render "show_follow"
  end

  def followers
     @title = "Followers"
     @user = User.find(params[:id])
     @users = @user.followers.paginate(page: params[:page])
     render "show_follow"
  end

  private
  def user_params
  	params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def correct_user
    if !current_user?(User.find_by(id: params[:id]))
      redirect_to root_path
    end
  end

  def admin_user
    redirect_to root_path unless current_user.admin?
  end

end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for (user, options={size:80})
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end

end

app/views/users/_follow.html.erb
<!--
That's no button for a link.
<%= link_to	"Follow", relationships_path(followed_id: @user.id), method: :post, class: "btn btn-primary" %>
-->

<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
<div><%= hidden_field_tag :followed_id, @user.id %></div>
<%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
	<div id="follow_form">
	<% if current_user.following?(@user) %>
		<%= render "unfollow" %>
	<% else %>
		<%= render "follow" %>
	<% end %>
	</div>
<% end %>

app/views/users/_form.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@user, url: locals[:path]) do |f| %>
			<%= render "shared/error_messages", object: @user %>

				<%= f.label :name, "Your Name" %>
				<%= f.text_field :name, class: 'form-control' %>
			
				<%= f.label :email, "Your Email Address" %>
				<%= f.email_field :email, class: 'form-control' %>
			
				<%= f.label :password, "Your Password" %>
				<%= f.password_field :password, class: 'form-control' %>
			
				<%= f.label :password_confirmation, "Password Confirmation" %>
				<%= f.password_field :password_confirmation, class: 'form-control' %>
			
				<%= f.submit locals[:submit_text], class: "btn btn-primary" %>
			

		<% end %>
	</div>
</div>

app/views/users/_unfollow.html.erb
<!--
That's no button for a link.
<%= link_to	"Unfollow", relationship_path(@user.id), method: :delete, class: "btn" %>
-->

<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id), html:{method: :delete}, remote: true) do |f| %>
	<%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit User") %>

<h1>Update your profile</h1>

<%= render 'form', :locals=>{:path => user_path(@user), :submit_text => "Save changes"} %>

app/views/users/index.html.erb
<% provide(:title, "All Users") %>
<h2> All Users </h2>
<%= will_paginate %>
<ul class="users" >
	<% @users.each do |user| %>
		<li>
			<%= gravatar_for user, size:50 %>
			<%= link_to user.name, user_path(user) %>
			<% if current_user.admin? && !current_user?(user) %>
			| <%= link_to "Delete", user_path(user), method: :delete, data:{confirm: "Are you sure?"}%>
			<% end %>

		</li>
	<% end %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, "Sign Up") %>

<h1>Sign Up</h1>

<%= render 'form', :locals=>{:path => signup_path, :submit_text => "Create my account"} %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
	<aside class="col-md-4">
		<section class="user_info">
			<h1>
				<%= gravatar_for(@user, size:80) %>
				<%= @user.name %> </br>
			</h1>
		</section>
		<section class="stats">
			<%= render "shared/stats", user: @user %>
		</section>
	</aside>


<!--
<p>
<%= @user.name %> <%= @user.email %>
</p>
<p>
	Created at:
	<%= @user.created_at %>
</p>
<p>
	Updated at:
	<%= @user.updated_at %>
</p>
<p>
	Time Now:
	<%= Time.now %>
</p>
-->

	<div class="col-md-8">
		<% if logged_in? %>
			<%= render "follow_form" %>
		<% end %>

		<% if @user.microposts.any? %>
			<h3>Microposts (<%= @user.microposts.count%>)</h3>
			<ol class="microposts">
				
				<%= render @microposts %>
				<%= will_paginate @microposts %>
			</ol>
		<% end %>
	</div>

</div>

app/views/users/show_follow.html.erb
<% provide :title, "#{@user.name}'s #{@title}" %>
<div class="row">
	<aside class="col-md-4">
		<section class="user_info">
			<%= gravatar_for(@user, size:80) %>
			<h1><%= @user.name %></h1>
			<span><%= link_to "View my profile", @user %> </span>
			<% if @user.microposts.any? %>
				<span><b>Microposts:</b> <%= @user.microposts.count%></span>
			<% end %>
			<h2>
		</section>

		<section class="stats">
			<%= render "shared/stats", user: @user %>
			<% if @users.any? %>
			<div class="user_avatars">
				<% @users.each do |user| %>
					<%= link_to gravatar_for(user, size:30), user %>
				<% end %>
			</div>
			<% end %>
		</section>
	</aside>


<!--
<p>
<%= @user.name %> <%= @user.email %>
</p>
<p>
	Created at:
	<%= @user.created_at %>
</p>
<p>
	Updated at:
	<%= @user.updated_at %>
</p>
<p>
	Time Now:
	<%= Time.now %>
</p>
-->

	<div class="col-md-8">
		<h3><%= @title%></h3>		
		<% if @users.any? %>
			<%= will_paginate @users%>
			<ul class="users" >
			<% @users.each do |user| %>
				<li>
					<%= gravatar_for user, size:50 %>
					<%= link_to user.name, user_path(user) %>
				</li>
			<% end %>
			</ul>
			<%= will_paginate @users%>	
		<% end %>	
	</div>

</div>