config/routes.rb
Rails.application.routes.draw do
 
  get 'microposts/create'

  get 'microposts/destroy'

  get 'password_resets/new'

  get 'password_resets/edit'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'sessions/new'

  get 'users/new'

  get '/help' => "static_pages#help"

  get '/about' => "static_pages#about"

  get '/contact' => "static_pages#contact"

  get '/signup' => "users#new"

  post '/signup' => "users#create"

  root 'static_pages#home'

  get '/login' => "sessions#new"

  post '/login' => "sessions#create"

  delete '/logout' => "sessions#destroy"

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :relationships, only:[:create, :destroy]

  resources :account_activations, only:[:edit]

  resources :password_resets, only:[:new, :create, :edit, :update]

  resources :microposts, only:[:create, :destroy]

end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  validates :content, presence: true, length:{maximum:140}
  validates :user_id, presence:true
  default_scope {order(created_at: :DESC)}
  mount_uploader :picture, PictureUploader
  validate :picture_size

  def picture_size
  	if picture.size > 5.megabytes
  		self.errors.add(:picture, "size should be less than 5MB.")
  	end
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only:[:create, :destroy]
  before_action :correct_user, only: [:destroy]


  def create
    @user = current_user
    @micropost = @user.microposts.new(micropost_params)
    if @micropost.save
      flash[:success] = "Your micropost is created."
      redirect_to root_path
  	else
      @feed_items = []
  		render "static_pages/home"
  	end
  end

  def destroy
    @micropost.destroy
    flash[:success] = "Micropost deleted."
    redirect_to request.referrer || root_path
  end

  private
  def micropost_params
  	params.require(:micropost).permit(:content, :picture)
  end

  def correct_user
    @micropost = current_user.microposts.find_by(id: params[:id])
    redirect_to root_path if @micropost.nil?     
  end

end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_micropost.html.erb
<li id="micropost-<%=micropost.id%>">
	<%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  	<span class="user"><%= link_to micropost.user.name, micropost.user %></span>
	<span class="content"><%=micropost.content%></span>
	<span class="timestamp">
		Posted <%=time_ago_in_words(micropost.created_at)%> ago.
		<% if current_user?(micropost.user) %>
			<%= link_to "Delete", micropost_path(micropost), method: :delete, data:{confirm:"Are you sure?"} %> 
		<% end %>
	</span>
	<%= image_tag micropost.picture.url if micropost.picture? %> 
</li> 

app/views/microposts/create.html.erb
<h1>Microposts#create</h1>
<p>Find me in app/views/microposts/create.html.erb</p>

app/views/microposts/destroy.html.erb
<h1>Microposts#destroy</h1>
<p>Find me in app/views/microposts/destroy.html.erb</p>